apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  namespace: n8n
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      containers:
        - name: n8n
          image: n8nio/n8n:2.20.6
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5678
          env:
          - name: WEBHOOK_URL
            value: http://n8n.kubernetes.local/
          - name: N8N_PROTOCOL
            value: http
          - name: N8N_HOST
            value: 0.0.0.0
          - name: N8N_PORT
            value: "5678"
          - name: N8N_SECURE_COOKIE
            value: "false"
          volumeMounts:
            - name: n8n-data
              mountPath: /home/node/.n8n
      volumes:
        - name: n8n-data
          persistentVolumeClaim:
            claimName: n8n-pvc
